name: Build

on:
  workflow_run:
    workflows: ["Test"]
    types: [completed]
    branches: [main]
  pull_request:
    types: [labeled]

env:
  GITLAB_REGISTRY: registry.gitlab.com

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
            echo ${{ github.ref_name }}
            echo '${{ toJSON(github) }}'
  build:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main' || (github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'DEPLOY')
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
            echo ${{ github.ref_name }}
            echo '${{ toJSON(github) }}'
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
            echo ${{ github.ref_name }}
