name: Test

on:
  push:
    branches:
      - "**"

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up environment
        run: |
          echo {{ github.ref_name }}
